### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by laalaguer** [laalaguer/VeChain-Address#1]
没 icon 不友好

**Comment by simplecooler** [comment]
Favicon?

**Comment by laalaguer** [comment]
ICON 需求在此

菜单栏和标题栏
![image](https://user-images.githubusercontent.com/6841046/44773561-796cea00-aba3-11e8-93ba-4cd4ced61e35.png)

Address界面
![image](https://user-images.githubusercontent.com/6841046/44773768-f730f580-aba3-11e8-89ea-46a6d7cf43fe.png)

Keystore生成后界面
![image](https://user-images.githubusercontent.com/6841046/44773854-30696580-aba4-11e8-9dff-c2df0e3c6be6.png)

**Comment by laalaguer** [comment]
11cb26046d2774fb68a58a63cfd079f9534cfeee
